kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{name}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
spec:
  image: {{image}}
  ingresses:
    {{#each ingresses}}
     - "{{this}}"
     {{/each}}
  liveness:
    path: /isAlive
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 30
  port: 8080
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: /isReady
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 30
  replicas:
    min: {{replicas.min}}
    max: {{replicas.max}}
  resources:
    limits:
      cpu: {{resources.limits.cpu}}
      memory: {{resources.limits.memory}}
    requests:
      cpu: {{resources.requests.cpu}}
      memory: {{resources.requests.memory}}
  cpuThresholdPercentage: 80
  webproxy: true
  envFrom:
    - secret: "{{ envFrom.secret }}"
  env:
    {{#each envs}}
    - name: "{{this.name}}"
      value: "{{this.value}}"
    {{/each}}
  tokenx:
    enabled: true
