kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: security-token-service
  namespace: {{namespace}}
  labels:
    team: plattformsikkerhet
spec:
  image: {{image}}
  ingresses:
    {{#each ingresses}}
     - "{{this}}"
     {{/each}}
  liveness:
    path: /isAlive
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /isReady
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  replicas:
    min: {{replicas.min}}
    max: {{replicas.max}}
  resources:
    limits:
      cpu: 800m
      memory: 3Gi
    requests:
      cpu: 600m
      memory: 3Gi
  cpuThresholdPercentage: 80
  vault:
    enabled: true
  paths:
    {{#each vault-paths}}
    - kvPath: "{{this.kvPath}}"
      mountPath: "{{this.mountPath}}"
    {{/each}}
  webproxy: true
  env:
    {{#each envs}}
    - name: "{{this.name}}"
      value: "{{this.value}}"
    {{/each}}
