kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{name}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
spec:
  image: {{image}}
  ingresses:
    {{#each ingresses}}
     - "{{this}}"
     {{/each}}
  liveness:
    path: /isAlive
    initialDelay: 80
    periodSeconds: 10
    failureThreshold: 30
  port: 8080
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: /isReady
    initialDelay: 80
    periodSeconds: 10
    failureThreshold: 30
  replicas:
    min: {{replicas.min}}
    max: {{replicas.max}}
  resources:
    limits:
      memory: {{limits.memory}}
    requests:
      cpu: "{{requests.cpu}}"
      memory: {{requests.memory}}
  webproxy: true
  envFrom:
    - secret: "{{ envFrom.secret }}"
  env:
    - name: JAVA_TOOL_OPTIONS
      value: "-Dhttp.proxyHost=webproxy.nais -Dhttps.proxyHost=webproxy.nais -Dhttp.proxyPort=8088 -Dhttps.proxyPort=8088 -Dhttp.nonProxyHosts=localhost|127.0.0.1|10.254.0.1|*.local|*.adeo.no|*.nav.no|*.aetat.no|*.devillo.no|*.oera.no|*.nais.io|*.aivencloud.com|*.intern.dev.nav.no|*.idporten.no"
    {{#each envs}}
    - name: "{{this.name}}"
      value: "{{this.value}}"
    {{/each}}
  tokenx:
    enabled: true
