kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{name}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{image}}
  ingresses:
    {{#each ingresses}}
     - "{{this}}"
     {{/each}}
  liveness:
    path: /isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  port: 8080
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: /isReady
    initialDelay: 30
    timeout: 1
  replicas:
    min: {{replicas.min}}
    max: {{replicas.max}}
  resources:
    limits:
      cpu: 800m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
  cpuThresholdPercentage: 80
  vault:
    enabled: true
    paths:
      {{#each vault-paths}}
      - kvPath: "{{this.kvPath}}"
        mountPath: "{{this.mountPath}}"
      {{/each}}
  webproxy: true
  env:
    {{#each envs}}
    - name: "{{this.name}}"
      value: "{{this.value}}"
    {{/each}}
