namespace: default
team: integrasjon
name: security-token-service
ingresses:
  - https://security-token-service.nais.adeo.no
envs:
  - name: APPLICATION_OIDC_ISSUER
    value: https://security-token-service.nais.adeo.no
  - name: SPRING_LDAP_BASE
    value: dc=adeo,dc=no
replicas:
  min: 2
  max: 4
vault-paths:
  - kvPath: serviceuser/data/prod/srvsecurity-token-service
    mountPath: /secrets/serviceuser
  - kvPath: oracle/data/prod/creds/securitytokenservice-user
    mountPath: /secrets/database/credentials
  - kvPath: oracle/data/prod/config/securitytokenservice
    mountPath: /secrets/database/config
  - kvPath: kv/prod/fss/security-token-service/default
    mountPath: /var/run/secrets/nais.io/vault
