server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
# Spring
spring:
  # Database
  datasource:
    url: <FROM ENV. VARS>
    username: <FROM ENV. VARS>
    password: <FROM ENV. VARS>
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
  jpa:
    open-in-view: false
    # For debugging
    show-sql: true
  profiles:
    active: remote
  main:
    banner-mode: 'off'
  # Ldap
  ldap:
    url: <FROM ENV. VARS>
    base: dc=test,dc=local
    port: <FROM ENV. VARS>
    timeout: 5000
# Application
application:
  oidc.issuer: <FROM ENV. VARS>
  service:
    username: <FROM ENV. VARS>
    passoword: <FROM ENV. VARS>
  # External
  external.issuer:
    openam: <FROM ENV. VARS>
    azuread: <FROM ENV. VARS>
    configuration.difi:
      oidc: <FROM ENV. VARS>
      maskinporten: <FROM ENV. VARS>
  jwks:
    endpoint:
      openam: <FROM ENV. VARS>
      azuread: <FROM ENV. VARS>
# Truststore & KeyStore
nav:
  truststore:
    path: <FROM ENV. VARS>
    password: <FROM ENV. VARS>
  keystore:
    file: <FROM ENV. VARS>
    password: <FROM ENV. VARS>
# Prometheus
management:
  health.defaults.enabled: false
  endpoint.prometheus.enabled: true
  endpoints.web:
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus
    base-path: /
# Logging
logging.config: classpath:logback-remote.xml
# Swagger
springdoc:
  api-docs:
    path: /api/api-doc
  swagger-ui:
    path: /api
  writer-with-default-pretty-printer: true
