server:
  port: 8080
  servlet:
    context-path: /rest
application:
  local:
    issuer: https://security-token-service.nais.preprod.local
    issuerSrvUser: srvUser
    openamIssuerUrl: https://
    openamJwksUrl: https://
    azureadIssuerUrl: https://
    azureadJwksUrl: https://
    difiConfigurationUrl: https://