package no.nav.gandalf.utils

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.node.ObjectNode
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import com.github.tomakehurst.wiremock.client.WireMock
import com.github.tomakehurst.wiremock.client.WireMock.aResponse
import com.github.tomakehurst.wiremock.client.WireMock.stubFor
import org.apache.http.HttpStatus
import java.nio.file.Files
import java.nio.file.Path

internal const val openAMResponseFileName = "openam-jwks.json"
internal const val openAMJwksUrl = "/isso/oauth2/connect/jwk_uri"

internal const val difiOIDCJwksUrl = "/jwk.json"
internal const val difiOIDCResponseFileName = "difi-oidc-jwks.json"
internal const val difiOIDCConfigurationUrl = "/.well-known/openid-configuration"
internal const val difiOIDCConfigurationResponseFileName = "difi-oidc-configuration.json"

internal const val difiMASKINPORTENCConfigurationUrl = "/.well-known/oauth-authorization-server"
internal const val difiMASKINPORTENCJwksUrl = "/jwk"
internal const val difiMASKINPORTENJWKSResponseFileName = "difi-maskinporten-jwks.json"
internal const val difiMASKINPORTENConfigurationResponseFileName = "difi-maskinporten-configuration.json"

internal const val azureADResponseFileName = "azuread-jwks.json"
internal const val azureADJwksUrl = "/discovery/v2.0/keys"

private val objectMapper: ObjectMapper = jacksonObjectMapper()

internal fun endpointStub(status: Int = HttpStatus.SC_OK, path: String, bodyFile: String) =
    stubFor(
        WireMock.get(WireMock.urlEqualTo(path))
            .willReturn(
                aResponse()
                    .withStatus(status)
                    .withHeader("Content-Type", "application/json; charset=UTF-8")
                    .withBodyFile(bodyFile),
            ),
    )

internal fun wellKnownStub(path: String, jwksUrl: String, bodyFile: String) {
    val content = Files.readString(Path.of("src/test/resources/__files/$bodyFile"))
    val jsonNode: JsonNode = objectMapper.readValue<JsonNode>(content).apply {
        (this as ObjectNode).put("jwks_uri", jwksUrl)
    }
    endpointStubWithBody(path = path, body = jsonNode)
}

internal fun endpointStubWithBody(status: Int = HttpStatus.SC_OK, path: String, body: Any) =
    stubFor(
        WireMock.get(WireMock.urlEqualTo(path))
            .willReturn(
                aResponse()
                    .withStatus(status)
                    .withHeader("Content-Type", "application/json; charset=UTF-8")
                    .withBody(objectMapper.writeValueAsString(body)),
            ),
    )

// Original REST-STS did not have token.
internal fun getAzureAdOIDC() =
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkN0VHVoTUptRDVNN0RMZHpEMnYyeDNRS1NSWSJ9.eyJhdWQiOiIxNWYwMWZlZS1iZDZkLTQ0MjctYmI3MC1mYzllNzVjYWExM2EiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vOTY2YWM1NzItZjViNy00YmJlLWFhODgtYzc2NDE5YzBmODUxL3YyLjAiLCJpYXQiOjE1OTEwOTQ2NjMsIm5iZiI6MTU5MTA5NDY2MywiZXhwIjoxNTkxMDk4NTYzLCJncm91cHMiOlsiMjhlNjZlNzctZDg3OS00N2YxLTg4MzUtZmVhNTA1Y2ZjZTlmIiwiNTA0NDUzNWQtMjQ1ZC00OWVmLTlhNzgtMmVmZWE2N2JhMGJjIiwiZDI5ODcxMDQtNjNiMi00MTEwLTgzYWMtMjBmZjZhZmUyNGEyIiwiZmVjNjYyOTItM2RkYi00OWJhLWEwY2YtY2FlZjQ2M2I3ZDYzIiwiYTlmNWVmODEtNGU4MS00MmU4LWIzNjgtMDI3MzA3MWI2NGI5IiwiMmZmZTMyNjItNmMwZS00NGYzLTk0ZjAtMzRkZmE1NjU5YTA0IiwiZjgxMTM4MTYtYjI0NC00MWU0LWFmMjktMzA4YjIzMTdhYTMzIiwiYTVjMjM3MGUtNmIzZC00YzJjLTlhNWUtMjM4MDA4NTI2NTc0IiwiZGU0NDA1MmQtYjA2Mi00NDk3LTg5YTItMGM4NWI5MzViODA4IiwiNjkwZmNjMzMtMmM0Yi00YWEzLTk4ZWUtN2MxNmRjYTI3NmZiIiwiOTI4NjM2ZjQtZmQwZC00MTQ5LTk3OGUtYTZmYjY4YmIxOWRlIiwiMTRlZDI2MmEtOGRjMC00ZWIxLTg1NDEtMTg1MzE1ZDBhYmJhIiwiYTNmOTE0OTMtMWFiOC00YjY0LWE1NDQtMGE3N2NiYmE5MjQwIiwiNDJmMzEzYjgtZDg4OC00MzQ0LTg2ZDYtYWRjYWVhNGVkMzgxIiwiMmRlYjMzNDEtMDUyYi00OGJhLTk1ZWEtMmIyMzUyYjQwZjYxIiwiYjFlMDQ0NjgtYTUzYS00OGZiLWEzZjctOTk2YzA2YzhjMTYzIiwiYzU3Yzg2ODgtYzY4MC00NWZiLWJlMjQtZTdkZGM0YzY5YjJkIiwiOTBmYzQ1MzUtYWI3NC00NDRlLTg5NjktMTkzNWI5NTYzZTAwIiwiOGJiOWI4ZDEtZjQ2YS00YWRlLThlZTgtNTg5NWVjY2RmOGNmIiwiN2M5MzhmMTgtMGY5OC00ZDM5LWFjNmYtNjBmNmZhNjlmMzNkIiwiOTI0YmFkY2QtYjkzNi00NGY0LWI3YmYtOTdjMDNkZTA4OTNhIiwiMTc0YmVjMjctZTk1NC00NTNiLTg0ODYtNGE4MGQ5ZmM3NjM2Il0sIm5hbWUiOiJGX1o5OTA1NDMgRV9aOTkwNTQzIiwibm9uY2UiOiJkY09KcW13bHZIUDVHWFNWZ2wzemJPcHF6ZmMxYzZjODl6Qm5SNXFSRnlZIiwib2lkIjoiODVjNTk1OWItZGU3OS00NDBkLTgwOTctNDE3YzczZTIxOTYyIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiejk5MDU0M0B0cnlnZGVldGF0ZW4ubm8iLCJzdWIiOiI2REpDcXFmV1phT2JpRllhXzlNOHhULU9VUkhqVk9LNHhrWnA4M1FwTjJrIiwidGlkIjoiOTY2YWM1NzItZjViNy00YmJlLWFhODgtYzc2NDE5YzBmODUxIiwidXRpIjoiaGI1VDE2MUh2VW1ncmZHV0lSNG1BQSIsInZlciI6IjIuMCJ9.phQbYVXP5zuv7iaBUXVQ1-89498NWqS9UMTM7ZFH1Qafl3-eTU8AW1fw-0hhA5JOarnj50xiE0nxjcohbKoVMO7zUQUfeGbl8AcRtDjhTScfv_PMd31fgyz8-NV6b83sedHfuDNlLIpahnqDWiFAO1fWLZ_IFxMgO11okeS98fKXW1b3FiyERbY7RsGkrokZN2srDAthY0t3ZPgMu3fcSfWmSW4SGkQVM4KloNocdgX8-6AV4qXMyZO9uBX8N_EJZscXgmVhg999M-tOY0bhv7WAKFvcK-anOUEzTgSTpF-ovnu6YBpl5695sASgqLHYHYc1fdDuNHXEP_Oxz69gvw"

internal fun getMaskinportenToken() =
    "eyJraWQiOiJBTUhVZWpoMnJWLUpCMU4teWJUVjhLNmQ5QlRFUEhEaTBYR29xUGxuNXprIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJ1bnNwZWNpZmllZCIsInNjb3BlIjoibmF2OnBlbnNqb25cL3YzXC9hbGRlcnNwZW5zam9uIiwiaXNzIjoiaHR0cHM6XC9cL3ZlcjIubWFza2lucG9ydGVuLm5vXC8iLCJjbGllbnRfYW1yIjoidmlya3NvbWhldHNzZXJ0aWZpa2F0IiwidG9rZW5fdHlwZSI6IkJlYXJlciIsImV4cCI6MTU4MTYwMjc5NSwiaWF0IjoxNTgxNjAyNjc1LCJjbGllbnRfaWQiOiI0NDEyMjZmOS0zOTgwLTRjY2MtOGIzOC1kZGQzN2U4MTZkMmEiLCJjbGllbnRfb3Jnbm8iOiI5ODI1ODM0NjIiLCJqdGkiOiJScndoTWFHelU0NmJ3WGpjZjlLX1V2OVMyQUZKMVNCWXpHd2hfUlZETmRBIiwiY29uc3VtZXIiOnsiYXV0aG9yaXR5IjoiaXNvNjUyMy1hY3RvcmlkLXVwaXMiLCJJRCI6IjAxOTI6OTgyNTgzNDYyIn19.w3Y62AGAyXpR7g-jQaKR7R7BaT1zUvfSV-HOlejKaeI2m6WQaN65pr9fXrtbFvIJp7Kbp6ezgpJ4Y6tUiDN1gYkYgMY5IOlDK4cvRqW3UuGkJ8Jt071xrCN-yco1iWm8TZ1lIpOCjuGNPYpJ6Fxp4c_nsIaXhQ1KD2HWAIUqUFUoDOp7Hd8fpxxcdq3O_mOxdXeEi4sS6BKpdMzxdQIRnEI_PEb-dqP4odKO9yAOvPNRhCbxYoBAYYUY2d2BbwLsy032OXvrTR2Y1zkthyeeH0n1eM0aOvxjFK9vuy0gODIpnnCGFE4HpnjwCZX6-sLPFCRuLZ244kpmN9cyU5jc4g"

internal fun getOpenAmOIDC() =
    "eyAidHlwIjogIkpXVCIsICJraWQiOiAiU0gxSWVSU2sxT1VGSDNzd1orRXVVcTE5VHZRPSIsICJhbGciOiAiUlMyNTYiIH0.eyAiYXRfaGFzaCI6ICJZNXgxcVNLclVVRlE3eVpEVVBIUXZBIiwgInN1YiI6ICJhZ2VudGFkbWluIiwgImF1ZGl0VHJhY2tpbmdJZCI6ICI0NWVkYmYwZS05NmIxLTRkODUtYWFlOC0xMzNmZDVlNmYzOGMtMzA4MDQ1IiwgImlzcyI6ICJodHRwczovL2lzc28tdC5hZGVvLm5vOjQ0My9pc3NvL29hdXRoMiIsICJ0b2tlbk5hbWUiOiAiaWRfdG9rZW4iLCAiYXVkIjogImZyZWctdG9rZW4tcHJvdmlkZXItdDAiLCAiY19oYXNoIjogInY3YW1vYl9lbjc2Tl9VRm5lZDFJaXciLCAib3JnLmZvcmdlcm9jay5vcGVuaWRjb25uZWN0Lm9wcyI6ICI2YjI3OWI0MC1iYjdhLTRjMmItYTQzNC01Y2YyYmNmMzcyMjUiLCAiYXpwIjogImZyZWctdG9rZW4tcHJvdmlkZXItdDAiLCAiYXV0aF90aW1lIjogMTUzOTY4MDMwMCwgInJlYWxtIjogIi8iLCAiZXhwIjogMTUzOTY4MzkwMCwgInRva2VuVHlwZSI6ICJKV1RUb2tlbiIsICJpYXQiOiAxNTM5NjgwMzAwIH0.CEPqay8UMpqVDUB9VMYMWtGgL5NoKY5fqy4-0216OxZ6zSQgUwJ9tqqMXD12yFNIACSOTTRdwahA0qgBDoRZH-u67mnEYXF_pFwhYpOWbwZy3W67B3re8dti8pMoCbFv0ydSifVkyDD44LEEUbnIBV-GvWgcY8E5pASwjycdRJAskCP3m2Bo9GY4XV10lDv59mM9G5wr3kpOn9iiPK0NFxdSizJZjh2qv9KtId9fuC7E-8SZvvUlKjChcIwP-gYiFkqce7KBhYkbwr9eYZ5wSwIY7107xAYVgKoRrjAbEm1okity6yEow0RwoEU-JlUe5Tbvd8mmjrJSHBEgEPiZyw"

internal fun getTokenDingsIdportenToken() =
    "eyJraWQiOiI3YmM4MjAxYS1lNDkxLTQxZDMtYjVlZC0zNTU1NjRjMjE4MDgiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiY2ZCRFJuODFYSkJnUG9NWVZyd2JFZyIsInN1YiI6IlFGeUJvYW9HQ2ZYV2hLR0tyQzl5dkVnY2lyTzdFblktNjVCU1kteGNrdG89IiwiYW1yIjpbIkJhbmtJRCJdLCJpc3MiOiJodHRwczpcL1wvdG9rZW5kaW5ncy5kZXYtZ2NwLm5haXMuaW8iLCJwaWQiOiIwODA4OTQwNjMxNiIsImxvY2FsZSI6Im5iIiwiY2xpZW50X2lkIjoiZGV2LWdjcDpwbGF0dGZvcm1zaWtrZXJoZXQ6ZGVidWctZGluZ3MiLCJzaWQiOiJRUWxzWTk5Qi1nQ0lHSGEtWHpVVXpzdHl4VjE1d3UwZmdyamZ5ZG5OSTRzIiwiYXVkIjoiZGV2LWdjcDpwbGF0dGZvcm1zaWtrZXJoZXQ6YXBpLWRpbmdzIiwiYWNyIjoiTGV2ZWw0IiwibmJmIjoxNjI5ODAzNzAxLCJpZHAiOiJodHRwczpcL1wvb2lkYy12ZXIyLmRpZmkubm9cL2lkcG9ydGVuLW9pZGMtcHJvdmlkZXJcLyIsImF1dGhfdGltZSI6MTYyOTgwMzQ4OSwiZXhwIjoxNjI5ODA0MDAxLCJpYXQiOjE2Mjk4MDM3MDEsImp0aSI6ImY4OGRjZjFkLWNlNDgtNDUwYy05MWExLWQwZThiYzdhZDNiZiJ9.nn2lF8H_GjlSYr_s7Mx_QRJMzK-_kiGIAUSZ4UQ1uT89luJ8juJbYQHykbiHiQmIF0Z5TEPgFO4Irc9GcKFVbUDRmAB7ucthCD3WBjSK1MUec_qTdynEtq3CxJMC1Edag2XN0GQLNO4ENHa0hqb9eKzMMS19W8fTw9P3ONPK4A-oi7WqvYCsNfozKsPtNuBSm0MkqKMjlEpAoXvF-TgMvm-JW9wuI3Y4DkTq7n1v0MnMJxnJAQ7twZgBcSx2Ff4Ck0uPXcvICCuvvr6EcNmNgWtBWRNwD3acOpSN17b-Tt78CdK-9-lp_SqV0Cl0g5UBKtH_Ph2s4kmkc12oY2HqxA"

internal fun getTokenDingsAzureADB2CToken() =
    "eyJraWQiOiJjZDg3NzQyZi0yZDliLTQxMzYtYjU4Yi04NTA3ODk3NjBhZjEiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiOHBDa2RHMGtLU1ZEZFZ1dnhrUzc5ZyIsInN1YiI6IjA4MDg5NDA2MzE2IiwidmVyIjoiMS4wIiwiaXNzIjoiaHR0cHM6XC9cL3Rva2VuZGluZ3MuZGV2LWdjcC5uYWlzLmlvIiwibm9uY2UiOiJvRTk2c0lXZjUyRTFqSkxIa1ZsV1ZNeXlaVmpKdG9JeFdnMzRWM0IycXpJIiwiY2xpZW50X2lkIjoiZGV2LWdjcDpwbGF0dGZvcm1zaWtrZXJoZXQ6ZGVidWctZGluZ3MiLCJhdWQiOiJkZXYtZ2NwOnBsYXR0Zm9ybXNpa2tlcmhldDphcGktZGluZ3MiLCJhY3IiOiJMZXZlbDQiLCJuYmYiOjE2Mjk4OTQzNTcsImlkcCI6Imh0dHBzOlwvXC9uYXZ0ZXN0YjJjLmIyY2xvZ2luLmNvbVwvZDM4ZjI1YWEtZWFiOC00YzUwLTlmMjgtZWJmOTJjMTI1NmYyXC92Mi4wXC8iLCJhdXRoX3RpbWUiOjE2Mjk4OTQyMzAsImV4cCI6MTYyOTg5NDY1NywiaWF0IjoxNjI5ODk0MzU3LCJqdGkiOiIwYmYyNjU4OC01YWUzLTRlYWItODdhYi0zNWIxMTUzNzdkZDIifQ.hD2WsbsU418iD8cJsTrhgFH71ZyIp2OXaCF-u5THeRCe9t7fR0_8wFx7uR2oVCJz1Q7oooO7DSQGDK0XE0lg15Ml5_Mh66rkSQCqqBRt9nkV49T7vtb_ttEsEMA4x1Q1SlZR7ysoMtxXc87APK90-WkUo5EzwWmwJxIoREXsHouuskRR_uN97Jc2vIJAhe6BZaN3pGsstycNepbVuK-xRXtW75_9LtzbFVPNnRjmIll4Bg-_R3WwTXTdjLjYP_A_NwBGmKOJR7Pc5tsH0IuT2rZnKR0gWeUmo8Q2HXvvxzaNh58LRB4IqcSctFbF7LXFFfzJoTyd50fqEMF5bqhgOw"

internal fun getIDPortenTokenAcrHigh() =
    "eyJraWQiOiJkaWdpdGFsaXNlcmluZ3NkaXJla3RvcmF0ZXQtLWNlcnQwIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIyMDkxODY5NzcwNiIsImFjciI6ImlkcG9ydGVuLWxvYS1oaWdoIiwic2NvcGUiOiJvcGVuaWQiLCJpc3MiOiJodHRwczovL3Rlc3QuaWRwb3J0ZW4ubm8iLCJjbGllbnRfYW1yIjoicHJpdmF0ZV9rZXlfand0IiwicGlkIjoiMjA5MTg2OTc3MDYiLCJleHAiOjE2OTM4MzA5NTEsImlhdCI6MTY5MzgyNzM1MSwianRpIjoiWjFscHo5TFR1RWciLCJjbGllbnRfaWQiOiIzMDJmYzUyOC05ZDc2LTQ4MWEtYmQ0Zi05MmE1NDBkNzM4YzgiLCJjb25zdW1lciI6eyJhdXRob3JpdHkiOiJpc282NTIzLWFjdG9yaWQtdXBpcyIsIklEIjoiMDE5Mjo4ODk2NDA3ODIifX0.bWuhRonP4cRwDeeAqglLN_jxDVjCgZwYdzAPwQSQ6cE1BcoRlNI-pPwbZNRzYIjVeLbDKz_4WuIscuy0yYHTlF7zliYqDpCOgIJ01oIV5l9T6-0vguEsQqZM-c_WJeZ71SV4FczXKBXfd3MT-B_4ggsIxOvsGnwbdZLJmcwxe-cVQusDBVudOD37TMMouQ6-nz_317yPH2zKIfkMLSxUX3kn38cRFo4a_T1acp2GaNOB_tVmjmYoXjWx5UIOsUYVkbgMHBlwvok8i4-BmmC0h3ZKj9SUXWsjcwGgnlXIHr7OBwz3Fo-ZgXsj8thJg0ww_rMys9FhZ60JVVbYwLWaz4orjgWuaCXLegLbp7G1rwY83JqwkvXN3vQI7SsiuQkqWJGJJtNFo_JZVmF-4Ov79xaZ5Fu7pA5jMI_r7pWD_ootNn-OkDW0VCpiabiVhAV7foX9fMbOCa2Ch7b8njEAmrXvf3GA0biI9bs9yhQT1OZefZBtQnJCKKwWjXbta8_x"

internal fun getIDPortenTokenAcrSubstantial() =
    "eyJraWQiOiJkaWdpdGFsaXNlcmluZ3NkaXJla3RvcmF0ZXQtLWNlcnQwIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIyMDkxODY5NzcwNiIsImFjciI6ImlkcG9ydGVuLWxvYS1zdWJzdGFudGlhbCIsInNjb3BlIjoib3BlbmlkIiwiaXNzIjoiaHR0cHM6Ly90ZXN0LmlkcG9ydGVuLm5vIiwiY2xpZW50X2FtciI6InByaXZhdGVfa2V5X2p3dCIsInBpZCI6IjIwOTE4Njk3NzA2IiwiZXhwIjoxNjkzODMxMDg4LCJpYXQiOjE2OTM4Mjc0ODgsImp0aSI6InJraUhodzgyT3lNIiwiY2xpZW50X2lkIjoiMzAyZmM1MjgtOWQ3Ni00ODFhLWJkNGYtOTJhNTQwZDczOGM4IiwiY29uc3VtZXIiOnsiYXV0aG9yaXR5IjoiaXNvNjUyMy1hY3RvcmlkLXVwaXMiLCJJRCI6IjAxOTI6ODg5NjQwNzgyIn19.QXRMo7WdLvc3XX7s8qF_60R-lQMESmnlVGzk_m9-vciwJzIyK6K-vWT_ja2cwm_BvymN13xrUcTv8c9SCvBX5ua2PvMFsj-8Q9YPGhJQqyQqNDtXjtCixElCR-44nOyekaocVPacuNfcm7WwJNn0OHMHWjJH2cxmgFUdmxFroDI7a5E0NxAsUfxAq4s_cYeiw7rRZ2n3XA_7y1CGmmWPom8WrwYM4UAEcXONpNkfIjCeSGdmXE4KAN3klZ-jqOvHPnyFyqfphUI8EZtE1U4PQBJHLFOKdhfkFFmTzWwo7lD7uN2kWg2aU_ut8IZAiEJYIsqpB0ugov5_Msqg72wYnhodcaYz2BDGRZgIOGtxrf4ILziRx4eGgkVOvDWKK4fwxgopqShsp3kbykuE3LskoNYh16qVbKGMV5DaSEquAX0Go1UI61WBuxJECKGebho8e82ZkpihN7cGbP-6Z0XeNf1yhtvpfVxMp7jDU4XvWlbDzQstDuLHrujNOcRhQRpf"
