name: PROD- Build, push, and deploy

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - master

env:
  IMAGE: ghcr.io/${{ github.repository }}/gandalf-security-token-service:${{ github.sha }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 15
          distribution: 'zulu'
          cache: 'gradle'
      - name: Run tests
        run: ./gradlew clean test
      - name: Unit tests results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-results
          path: build/reports/tests

  build:
    name: Build and push Docker container
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 15
          distribution: 'zulu'
          cache: 'gradle'
      - name: Build JAR
        run: ./gradlew bootJar -x test

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SALSA_CREDENTIALS }}

      - name: NAIS SLSA Provenance Action
        uses: nais/salsa@v0.6
        with:
          key: ${{ secrets.SALSA_KMS_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy-dev-t4:
    name: Deploy to NAIS dev (old t4)
    needs: build
    if: "github.ref == 'refs/heads/master'"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_AURA_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/nais.yml
          VARS: .nais/t4-vars.yml

  #deploy-dev:
  #  name: Deploy to NAIS dev
  #  needs: [build, deploy-dev-t4]
  #  if: "github.ref == 'refs/heads/master'"
  #  runs-on: ubuntu-20.04
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: nais/deploy/actions/deploy@v1
  #      env:
  #        APIKEY: ${{ secrets.NAIS_AURA_DEPLOY_APIKEY }}
  #        CLUSTER: dev-fss
  #        RESOURCE: .nais/nais.yml
  #        VARS: .nais/default-vars.yml
#
  #deploy-prod:
  #  name: Deploy to NAIS prod
  #  needs: [deploy-dev, deploy-dev-t4]
  #  if: "github.ref == 'refs/heads/master'"
  #  runs-on: ubuntu-20.04
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: nais/deploy/actions/deploy@v1
  #      env:
  #        APIKEY: ${{ secrets.NAIS_AURA_DEPLOY_APIKEY }}
  #        CLUSTER: prod-fss
  #        RESOURCE: .nais/nais.yml
  #        VARS: .nais/prod-vars.yml
