name: DEV - Build, push, and deploy

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - "release/**"

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/gandalf-security-token-service:${{ github.sha }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3.0.0
        with:
          java-version: 14
          distribution: 'zulu'
          cache: 'gradle'
      - name: Run tests
        run: ./gradlew clean test
      - name: Unit tests results
        if: always()
        uses: actions/upload-artifact@v2.3.1
        with:
          name: unit-tests-results
          path: build/reports/tests

  build:
    name: Build and push Docker container
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3.0.0
        with:
          java-version: 14
          distribution: 'zulu'
          cache: 'gradle'
      - name: Build JAR
        run: ./gradlew bootJar -x test
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build . --pull --tag ${IMAGE}
          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin https://docker.pkg.github.com
          docker push ${IMAGE}

  deploy-dev:
    name: Deploy to NAIS dev
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_AURA_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/nais.yml
          VARS: .nais/default-vars.yml
