name: TEST - Build, push, and deploy

on:
  push:
    branches:
      - 'test/**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/test-gandalf-security-token-service:${{ github.sha }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 14
          distribution: 'zulu'
          cache: 'gradle'
      - name: Run tests
        run: ./gradlew clean test

  build:
    name: Build and push Docker container
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 14
          distribution: 'zulu'
          cache: 'gradle'
      - name: Build JAR
        run: ./gradlew bootJar -x test
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build . --pull --tag ${IMAGE}
          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin https://docker.pkg.github.com
          docker push ${IMAGE}

  deploy-dev-t5:
    name: Deploy to NAIS dev (t5)
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/naiserator.yml
          VARS: .nais/test-vars.yml
