name: DEV - Build, push, and deploy

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - "release/**"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 15
          distribution: 'zulu'
          cache: 'gradle'
      - name: Run tests
        run: ./gradlew clean test
      - name: Unit tests results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-results
          path: build/reports/tests

  build:
    name: Build and push Docker container
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-20.04
    outputs:
      "image": ${{ steps.docker-build-push.outputs.image }}
    permissions:
      packages: "write"
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 15
          distribution: 'zulu'
          cache: 'gradle'
      - name: Build JAR
        run: ./gradlew bootJar -x test

      - name: Push docker image to GAR and sign image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: aura
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # Provided as Organization Secret
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # Provided as Organization Variable

  deploy-dev-dev:
    name: Deploy to NAIS dev dev
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_AURA_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/nais.yml
          VARS: .nais/t4-vars.yml
          VAR: image=${{ needs.build.outputs.image }}

  deploy-dev:
    name: Deploy to NAIS dev
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_AURA_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/nais.yml
          VARS: .nais/default-vars.yml
          VAR: image=${{ needs.build.outputs.image }}
