name: PROD- Build, push, and deploy

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'
      - name: Run tests
        run: ./gradlew clean test
      - name: Unit tests results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-results
          path: build/reports/tests

  build:
    name: Build and push Docker container
    needs: test
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-20.04
    outputs:
      "image": ${{ steps.docker-build-push.outputs.image }}
    permissions:
      packages: "write"
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'
      - name: Build JAR
        run: ./gradlew bootJar -x test

      - name: Push docker image to GAR and sign image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: aura
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # Provided as Organization Secret
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # Provided as Organization Variable

      - name: Upload salsa
        uses: actions/upload-artifact@v3
        with:
          name: salsa
          path: ${{ steps.docker-build-push.outputs.salsa }}

  deploy-dev-t4:
    name: Deploy to NAIS dev (old t4)
    needs: build
    if: "github.ref == 'refs/heads/master'"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_AURA_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/nais.yml
          VARS: .nais/t4-vars.yml
          VAR: image=${{ needs.build.outputs.image }}
          TIMEOUT: 15m

  deploy-dev:
    name: Deploy to NAIS dev
    needs: [ build, deploy-dev-t4 ]
    if: "github.ref == 'refs/heads/master'"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_AURA_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/nais.yml
          VARS: .nais/default-vars.yml
          VAR: image=${{ needs.build.outputs.image }}
          TIMEOUT: 15m

# deploy-prod:
#   name: Deploy to NAIS prod
#   needs: [ build, deploy-dev, deploy-dev-t4 ]
#   if: "github.ref == 'refs/heads/master'"
#   runs-on: ubuntu-20.04
#   steps:
#     - uses: actions/checkout@v4
#     - uses: nais/deploy/actions/deploy@v1
#       env:
#         APIKEY: ${{ secrets.NAIS_AURA_DEPLOY_APIKEY }}
#         CLUSTER: prod-fss
#         RESOURCE: .nais/nais.yml
#         VARS: .nais/prod-vars.yml
#         VAR: image=${{ needs.build.outputs.image }}
#         TIMEOUT: 15m
